### ISSUE TITLE
Token selection modal: should save custom token in user's token list

### ISSUE THREAD

**Issue by wildmolasses** [ScopeLift/token-shielder#125]
waiting to hear: should we save just for the session, or persist between sessions?

> When you add a custom token, it does not save it in the menu of tokens a user can select

https://user-images.githubusercontent.com/5423313/228402041-4c229d8d-a1a0-4b69-8097-11fabc49bbe3.mp4

**Comment by alexkeating** [comment]
Seems like multiple sessions is preferred
