### ISSUE TITLE
Unstoppable domain resolution

### ISSUE THREAD

**Issue by wildmolasses** [ScopeLift/token-shielder#19]
From reqs: 

> Unstoppable Domain resolver: something.crypto -> 0zk123…456

Use the [resolution library](https://github.com/unstoppabledomains/resolution) to resolve unstoppable domain names in the recipient address field. Implementer could decide whether the result of the resolution belongs on the form, or should be deferred until the "transaction review" in #17

**Comment by mds1** [comment]
For examples of how to handle the resolution, see here: https://github.com/Railgun-Privacy/frontend-react-private/blob/32586b0e1a1670a2f405000a39f8714468717e78/src/hooks/addresses/useAddressResolver.tsx#L33
