### ISSUE TITLE
Create "URL link generator" component

### ISSUE THREAD

**Issue by wildmolasses** [ScopeLift/token-shielder#20]
From reqs:

> URL link generator for: [www.DOMAIN.com/send/0zk123...456](http://www.domain.com/send/0zk123...456) or [www.DOMAIN.com/send/something.crypto](http://www.domain.com/send/something.crypto), which would prefill the “to” field.

Let's create a small component that takes an input value and generates a send link for the user.

**Comment by alexkeating** [comment]
Where do you guys think this component will go @wildmolasses @mds1? Would it be a separate page or a button under the form?

**Comment by mds1** [comment]
Wdyt of doing it like we have on Umbra, where you fill out the form and then can either use that form info to send (here, shield) or use it to creat a payment link? Though if we don't actually support all the fields and it's only "to" hat we support, maybe a separate page is better?

**Comment by mds1** [comment]
Actually, I think we should just do it on the same page with a secondary style button, like Umbra. We can address any UX confusion with a tooltip or something that indicates only the address is used for payment links. But adding a second page feels like it'd be more work for minimal benefit
