### ISSUE TITLE
Fix error in the console

### ISSUE THREAD

**Issue by alexkeating** [ScopeLift/token-shielder#72]
Seeing this error in the console, it was also present in #68, so we can pull out into a separate issue if needed 
<img width="686" alt="image" src="https://user-images.githubusercontent.com/17163988/215100486-612df6a9-8d5d-4939-8673-344e1962cfb0.png">

_Originally posted by @mds1 in https://github.com/ScopeLift/railgun-shielder/pull/70#discussion_r1088972705_

**Comment by mds1** [comment]
Closing, as this is no longer present
