### ISSUE TITLE
Fix gradient background repeat

### ISSUE THREAD

**Issue by wildmolasses** [ScopeLift/token-shielder#81]
<img width="1716" alt="Screenshot 2023-01-31 at 1 00 54 PM" src="https://user-images.githubusercontent.com/5423313/215848853-a5a28f8d-5739-445f-bfb0-7eca62fa36c6.png">

**Comment by mds1** [comment]
What browser / monitor resolution are you using? I'm not able to reproduce this. Also it seems you have darkreader or a similar extension enabled which may be messing with the colors/repeating

**Comment by mds1** [comment]
Ah ok, actually I am able to reproduce this when the console is open. Can you confirm that's the only time the issue arises for you

**Comment by wildmolasses** [comment]
@mds1 fixed this in #116 , cheers
